#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
COMPOSED = ROOT.parent
HEADER = COMPOSED / "c/parser.h"
SPEC = ROOT / "generated/binding_spec.json"
OUTPUT = ROOT / "go-host/binding_gen.go"
GENERATOR_ID = "composed-binding-generator-0.2.0"


def normalized_source() -> str:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    header_hash = hashlib.sha256(HEADER.read_bytes()).hexdigest()
    spec_hash = hashlib.sha256(
        json.dumps(spec, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()
    raw = f"""// Code generated by {GENERATOR_ID}; DO NOT EDIT.
package main

/*
#cgo CFLAGS: -I../../c
#include "../../c/parser.c"
*/
import "C"
import "unsafe"

const BindingGeneratorID = "{GENERATOR_ID}"
const BindingHeaderSHA256 = "{header_hash}"
const BindingSpecSHA256 = "{spec_hash}"
const BindingABIVersion = {spec["abi_version"]}

func parseNative(b []byte) (uint32, int) {{
\tif len(b) == 0 {{
\t\treturn 0, 1
\t}}
\tvar out C.uint32_t
\trc := C.mncs_parse_u32((*C.uint8_t)(unsafe.Pointer(&b[0])), C.size_t(len(b)), &out)
\treturn uint32(out), int(rc)
}}
"""
    with tempfile.NamedTemporaryFile("w", suffix=".go", delete=False) as temporary:
        temporary.write(raw)
        temporary_path = pathlib.Path(temporary.name)
    try:
        subprocess.run(["gofmt", "-w", str(temporary_path)], check=True)
        return temporary_path.read_text(encoding="utf-8")
    finally:
        temporary_path.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--print-identity", action="store_true")
    args = parser.parse_args()
    output = normalized_source()
    if args.print_identity:
        print(hashlib.sha256(output.encode()).hexdigest())
        return 0
    if args.check:
        return 0 if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == output else 1
    OUTPUT.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
