#!/usr/bin/env python3
"""Shared identity and gate builders for EdgeStream evidence packaging."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
EVIDENCE = ROOT / "evidence"
RESULTS = EVIDENCE / "results"
CONTRACT_ID = "mncs.edgestream.telemetry.v1"
STAMP_START = "2026-07-26T22:00:00Z"
STAMP_END = "2026-07-26T23:00:00Z"


def digest(path: Path) -> str:
    """Return the MNCS-formatted SHA-256 identity for a regular file."""

    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def read_json(path: Path) -> dict[str, Any]:
    """Read one JSON object generated by the study harness."""

    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise TypeError(f"expected JSON object: {path}")
    return value


def write_json(path: Path, value: Any) -> None:
    """Write stable, readable JSON with a trailing newline."""

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def identity(
    identity_id: str,
    kind: str,
    name: str,
    version: str,
    description: str,
    attributes: dict[str, Any],
) -> Path:
    """Create one MNCS identity record and return its path."""

    path = EVIDENCE / "identities" / f"{identity_id}.json"
    write_json(
        path,
        {
            "schema_version": "0.2",
            "mncs_version": "0.2",
            "identity_id": identity_id,
            "identity_kind": kind,
            "name": name,
            "version": version,
            "description": description,
            "attributes": attributes,
            "extensions": {},
        },
    )
    return path


def gate(
    result_id: str,
    gate_kind: str,
    status: str,
    raw_evidence_id: str,
    machine_hash: str,
    reference_hash: str,
    evaluator_hash: str,
    environment_hash: str,
    observations: int,
    limitations: list[str] | None = None,
) -> Path:
    """Create one content-bound MNCS gate result."""

    path = EVIDENCE / "gates" / f"{result_id}.json"
    default_limitations = [
        "Experimental local development evidence; not an accredited assurance claim."
    ]
    write_json(
        path,
        {
            "schema_version": "0.2",
            "mncs_version": "0.2",
            "result_id": result_id,
            "gate_kind": gate_kind,
            "contract_id": CONTRACT_ID,
            "component_identity": {
                "name": "EdgeStream",
                "version": "0.1.0-development",
                "identity_hash": machine_hash,
            },
            "candidate_source_hash": machine_hash,
            "reference_source_hash": reference_hash,
            "evaluator": {
                "name": "EdgeStream study evaluator",
                "version": "1.0",
                "identity_hash": evaluator_hash,
                "identity_evidence_id": "identity-evaluator",
            },
            "environment": {
                "fingerprint": environment_hash,
                "identity_evidence_id": "identity-environment",
            },
            "status": status,
            "started_at": STAMP_START,
            "completed_at": STAMP_END,
            "observation_counts": {
                "total": observations,
                "passed": observations if status == "PASS" else 0,
                "failed": observations if status == "FAIL" else 0,
                "unknown": observations if status == "UNKNOWN" else 0,
            },
            "evidence_references": [
                "contract",
                "reference",
                "machine",
                "identity-evaluator",
                "identity-environment",
                raw_evidence_id,
            ],
            "assumptions": [
                "The checked-in contract and declared environment delimit this result."
            ],
            "limitations": limitations or default_limitations,
            "extensions": {},
        },
    )
    return path


def create_identities(
    harness: Path,
    corpus: Path,
    environment: dict[str, Any],
) -> dict[str, Path]:
    """Create every identity used by the L4 evidence graph."""

    return {
        "generator": identity(
            "identity-generator",
            "generator",
            "EdgeStream deterministic specialization generator",
            "1.0",
            "Transforms the readable C11 reference into the table-specialized candidate.",
            {
                "network_access": False,
                "deterministic": True,
                "source": "generator/generate_candidate.py",
            },
        ),
        "evaluator": identity(
            "identity-evaluator",
            "evaluator",
            "EdgeStream study evaluator",
            "1.0",
            (
                "Runs differential, mutation, recovery, compiler, sanitizer, "
                "structural, and benchmark gates."
            ),
            {"source_sha256": digest(harness), "repetitions": 7},
        ),
        "environment": identity(
            "identity-environment",
            "environment",
            "EdgeStream local development environment",
            "2026-07-26",
            (
                "Captured host, compiler, and interpreter environment for the "
                "checked-in development run."
            ),
            {
                "platform": str(environment["platform"]),
                "machine": str(environment["machine"]),
                "python": str(environment["python"]),
            },
        ),
        "compiler": identity(
            "identity-compiler",
            "compiler",
            "GCC and Clang strict C11 matrix",
            "1.0",
            "Strict-warning compiler matrix used by the development run.",
            {
                "gcc": str(environment.get("gcc")),
                "clang": str(environment.get("clang")),
            },
        ),
        "benchmark": identity(
            "identity-benchmark",
            "benchmark_harness",
            "EdgeStream paired benchmark harness",
            "1.0",
            "Counterbalanced paired measurements with no outlier deletion.",
            {"source_sha256": digest(harness), "threshold": 1.15},
        ),
        "corpus": identity(
            "identity-corpus",
            "corpus",
            "EdgeStream deterministic workload corpus",
            "1.0",
            ("Steady, hostile, high-cardinality, and sequence/time edge-case workloads."),
            {"manifest_sha256": digest(corpus), "generated": True},
        ),
        "build": identity(
            "identity-build",
            "build",
            "EdgeStream strict C11 build",
            "1.0",
            ("Optimized local binaries built from the indexed reference and candidate sources."),
            {"optimization": "O3", "language": "C11"},
        ),
    }


def create_gate_results(
    machine_hash: str,
    reference_hash: str,
    evaluator_hash: str,
    environment_hash: str,
) -> list[Path]:
    """Create the non-performance gate records required for MNCS-L4."""

    raw_ids = {
        "differential": "raw-differential",
        "compiler-matrix": "raw-compiler-matrix",
        "sanitizers": "raw-sanitizers",
        "checkpoint-recovery": "raw-checkpoint-recovery",
        "mutation": "raw-mutation",
        "structural": "raw-structural",
    }
    shared = (machine_hash, reference_hash, evaluator_hash, environment_hash)
    return [
        gate(
            "gate-behavioral",
            "behavioral",
            "PASS",
            raw_ids["differential"],
            *shared,
            28,
        ),
        gate(
            "gate-compiler-matrix",
            "compiler_matrix",
            "PASS",
            raw_ids["compiler-matrix"],
            *shared,
            4,
        ),
        gate(
            "gate-safety",
            "safety",
            "PASS",
            raw_ids["sanitizers"],
            *shared,
            2,
        ),
        gate(
            "gate-resource-bounds",
            "resource_bounds",
            "PASS",
            raw_ids["checkpoint-recovery"],
            *shared,
            10,
        ),
        gate(
            "gate-mutation",
            "mutation",
            "PASS",
            raw_ids["mutation"],
            *shared,
            1,
        ),
        gate(
            "gate-structural",
            "structural",
            "PASS",
            raw_ids["structural"],
            *shared,
            7,
            [
                "The required provider is the bounded source checker; Joern-specific "
                "evidence is separately UNKNOWN and is not required for this claim."
            ],
        ),
    ]


def create_invariant(
    machine_hash: str,
    evaluator_hash: str,
    environment_hash: str,
) -> Path:
    """Create the bounded-storage structural invariant result."""

    path = EVIDENCE / "invariants" / "invariant-bounded-storage.json"
    write_json(
        path,
        {
            "schema_version": "0.2",
            "mncs_version": "0.2",
            "result_id": "invariant-bounded-storage",
            "invariant_id": "bounded-storage",
            "requirement": (
                "The processor uses fixed-capacity device, metric, window, and parser "
                "storage and contains no processor-path dynamic allocation."
            ),
            "contract_id": CONTRACT_ID,
            "candidate_source_hash": machine_hash,
            "evaluator_identity_hash": evaluator_hash,
            "evaluator_identity_id": "identity-evaluator",
            "environment_fingerprint": environment_hash,
            "status": "PASS",
            "provider": "edgestream-structural-checker",
            "provider_version": "1.0",
            "analysis_method": (
                "Bounded source-pattern checks tied to declared constants and the "
                "generated candidate identity."
            ),
            "assumptions": ["The C compiler preserves the declared fixed object bounds."],
            "boundedness": {
                "bounded": True,
                "description": "Seven explicit source checks over one candidate source file.",
            },
            "locations": [
                {
                    "path": "machine/edgestream_generated.c",
                    "line": 1,
                    "message": "Generated candidate and fixed-capacity state.",
                }
            ],
            "started_at": STAMP_START,
            "completed_at": STAMP_END,
            "limitations": [
                "Pattern analysis is a rejection gate and does not prove complete C semantics."
            ],
            "extensions": {},
        },
    )
    return path
