/* MNCS-GENERATED
 * Generated by generator/generate_candidate.py from the readable reference.
 * Do not edit this file directly.
 */
#include "edgestream.h"

#include <errno.h>
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>

#define ES_CHECKPOINT_MAGIC "ESCP"
#define ES_CHECKPOINT_VERSION 1u

static uint16_t read_u16(const uint8_t *p) {
    return (uint16_t)((uint16_t)p[0] | (uint16_t)((uint16_t)p[1] << 8u));
}

static uint32_t read_u32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8u) | ((uint32_t)p[2] << 16u) |
           ((uint32_t)p[3] << 24u);
}

static uint64_t read_u64(const uint8_t *p) {
    uint64_t value = 0;
    for (unsigned i = 0; i < 8; ++i) {
        value |= (uint64_t)p[i] << (8u * i);
    }
    return value;
}

/* MNCS-GENERATED: table specialized for the declared CRC-32 polynomial. */
static const uint32_t crc32_table[256] = {
    0x00000000u, 0x77073096u, 0xee0e612cu, 0x990951bau, 0x076dc419u, 0x706af48fu, 0xe963a535u, 0x9e6495a3u,
    0x0edb8832u, 0x79dcb8a4u, 0xe0d5e91eu, 0x97d2d988u, 0x09b64c2bu, 0x7eb17cbdu, 0xe7b82d07u, 0x90bf1d91u,
    0x1db71064u, 0x6ab020f2u, 0xf3b97148u, 0x84be41deu, 0x1adad47du, 0x6ddde4ebu, 0xf4d4b551u, 0x83d385c7u,
    0x136c9856u, 0x646ba8c0u, 0xfd62f97au, 0x8a65c9ecu, 0x14015c4fu, 0x63066cd9u, 0xfa0f3d63u, 0x8d080df5u,
    0x3b6e20c8u, 0x4c69105eu, 0xd56041e4u, 0xa2677172u, 0x3c03e4d1u, 0x4b04d447u, 0xd20d85fdu, 0xa50ab56bu,
    0x35b5a8fau, 0x42b2986cu, 0xdbbbc9d6u, 0xacbcf940u, 0x32d86ce3u, 0x45df5c75u, 0xdcd60dcfu, 0xabd13d59u,
    0x26d930acu, 0x51de003au, 0xc8d75180u, 0xbfd06116u, 0x21b4f4b5u, 0x56b3c423u, 0xcfba9599u, 0xb8bda50fu,
    0x2802b89eu, 0x5f058808u, 0xc60cd9b2u, 0xb10be924u, 0x2f6f7c87u, 0x58684c11u, 0xc1611dabu, 0xb6662d3du,
    0x76dc4190u, 0x01db7106u, 0x98d220bcu, 0xefd5102au, 0x71b18589u, 0x06b6b51fu, 0x9fbfe4a5u, 0xe8b8d433u,
    0x7807c9a2u, 0x0f00f934u, 0x9609a88eu, 0xe10e9818u, 0x7f6a0dbbu, 0x086d3d2du, 0x91646c97u, 0xe6635c01u,
    0x6b6b51f4u, 0x1c6c6162u, 0x856530d8u, 0xf262004eu, 0x6c0695edu, 0x1b01a57bu, 0x8208f4c1u, 0xf50fc457u,
    0x65b0d9c6u, 0x12b7e950u, 0x8bbeb8eau, 0xfcb9887cu, 0x62dd1ddfu, 0x15da2d49u, 0x8cd37cf3u, 0xfbd44c65u,
    0x4db26158u, 0x3ab551ceu, 0xa3bc0074u, 0xd4bb30e2u, 0x4adfa541u, 0x3dd895d7u, 0xa4d1c46du, 0xd3d6f4fbu,
    0x4369e96au, 0x346ed9fcu, 0xad678846u, 0xda60b8d0u, 0x44042d73u, 0x33031de5u, 0xaa0a4c5fu, 0xdd0d7cc9u,
    0x5005713cu, 0x270241aau, 0xbe0b1010u, 0xc90c2086u, 0x5768b525u, 0x206f85b3u, 0xb966d409u, 0xce61e49fu,
    0x5edef90eu, 0x29d9c998u, 0xb0d09822u, 0xc7d7a8b4u, 0x59b33d17u, 0x2eb40d81u, 0xb7bd5c3bu, 0xc0ba6cadu,
    0xedb88320u, 0x9abfb3b6u, 0x03b6e20cu, 0x74b1d29au, 0xead54739u, 0x9dd277afu, 0x04db2615u, 0x73dc1683u,
    0xe3630b12u, 0x94643b84u, 0x0d6d6a3eu, 0x7a6a5aa8u, 0xe40ecf0bu, 0x9309ff9du, 0x0a00ae27u, 0x7d079eb1u,
    0xf00f9344u, 0x8708a3d2u, 0x1e01f268u, 0x6906c2feu, 0xf762575du, 0x806567cbu, 0x196c3671u, 0x6e6b06e7u,
    0xfed41b76u, 0x89d32be0u, 0x10da7a5au, 0x67dd4accu, 0xf9b9df6fu, 0x8ebeeff9u, 0x17b7be43u, 0x60b08ed5u,
    0xd6d6a3e8u, 0xa1d1937eu, 0x38d8c2c4u, 0x4fdff252u, 0xd1bb67f1u, 0xa6bc5767u, 0x3fb506ddu, 0x48b2364bu,
    0xd80d2bdau, 0xaf0a1b4cu, 0x36034af6u, 0x41047a60u, 0xdf60efc3u, 0xa867df55u, 0x316e8eefu, 0x4669be79u,
    0xcb61b38cu, 0xbc66831au, 0x256fd2a0u, 0x5268e236u, 0xcc0c7795u, 0xbb0b4703u, 0x220216b9u, 0x5505262fu,
    0xc5ba3bbeu, 0xb2bd0b28u, 0x2bb45a92u, 0x5cb36a04u, 0xc2d7ffa7u, 0xb5d0cf31u, 0x2cd99e8bu, 0x5bdeae1du,
    0x9b64c2b0u, 0xec63f226u, 0x756aa39cu, 0x026d930au, 0x9c0906a9u, 0xeb0e363fu, 0x72076785u, 0x05005713u,
    0x95bf4a82u, 0xe2b87a14u, 0x7bb12baeu, 0x0cb61b38u, 0x92d28e9bu, 0xe5d5be0du, 0x7cdcefb7u, 0x0bdbdf21u,
    0x86d3d2d4u, 0xf1d4e242u, 0x68ddb3f8u, 0x1fda836eu, 0x81be16cdu, 0xf6b9265bu, 0x6fb077e1u, 0x18b74777u,
    0x88085ae6u, 0xff0f6a70u, 0x66063bcau, 0x11010b5cu, 0x8f659effu, 0xf862ae69u, 0x616bffd3u, 0x166ccf45u,
    0xa00ae278u, 0xd70dd2eeu, 0x4e048354u, 0x3903b3c2u, 0xa7672661u, 0xd06016f7u, 0x4969474du, 0x3e6e77dbu,
    0xaed16a4au, 0xd9d65adcu, 0x40df0b66u, 0x37d83bf0u, 0xa9bcae53u, 0xdebb9ec5u, 0x47b2cf7fu, 0x30b5ffe9u,
    0xbdbdf21cu, 0xcabac28au, 0x53b39330u, 0x24b4a3a6u, 0xbad03605u, 0xcdd70693u, 0x54de5729u, 0x23d967bfu,
    0xb3667a2eu, 0xc4614ab8u, 0x5d681b02u, 0x2a6f2b94u, 0xb40bbe37u, 0xc30c8ea1u, 0x5a05df1bu, 0x2d02ef8du,
};

static uint32_t crc32_slow(const uint8_t *data, size_t length) {
    uint32_t crc = 0xffffffffu;
    for (size_t i = 0; i < length; ++i) {
        crc = crc32_table[(crc ^ data[i]) & 0xffu] ^ (crc >> 8u);
    }
    return ~crc;
}

static void emit(FILE *out, bool quiet, const char *text) {
    if (!quiet) {
        fputs(text, out);
        fputc('\n', out);
    }
}

static void emit_reject(es_processor *p, FILE *out, const char *reason) {
    char line[160];
    p->rejected++;
    (void)snprintf(line, sizeof(line),
                   "{\"type\":\"reject\",\"reason\":\"%s\",\"rejected\":%" PRIu64 "}",
                   reason, p->rejected);
    emit(out, p->quiet, line);
}

static es_device_state *find_device(es_processor *p, uint32_t id, FILE *out) {
    es_device_state *free_slot = NULL;
    for (size_t i = 0; i < ES_MAX_DEVICES; ++i) {
        if (p->devices[i].used && p->devices[i].device_id == id) {
            return &p->devices[i];
        }
        if (!p->devices[i].used && free_slot == NULL) {
            free_slot = &p->devices[i];
        }
    }
    if (free_slot == NULL) {
        char line[160];
        (void)snprintf(line, sizeof(line),
                       "{\"type\":\"resource_limit\",\"resource\":\"active_devices\",\"device\":%u}",
                       id);
        emit(out, p->quiet, line);
        return NULL;
    }
    memset(free_slot, 0, sizeof(*free_slot));
    free_slot->used = true;
    free_slot->device_id = id;
    return free_slot;
}

static void emit_silence(es_processor *p, FILE *out, uint64_t watermark) {
    for (size_t i = 0; i < ES_MAX_DEVICES; ++i) {
        es_device_state *device = &p->devices[i];
        if (!device->used || device->last_timestamp == 0) {
            continue;
        }
        bool silent = watermark > device->last_timestamp &&
                      watermark - device->last_timestamp > ES_SILENCE_MS;
        if (silent && !device->silence_alarm) {
            char line[192];
            device->silence_alarm = true;
            (void)snprintf(line, sizeof(line),
                           "{\"type\":\"alarm\",\"alarm\":\"silence\",\"state\":\"active\",\"device\":%u,\"watermark\":%" PRIu64 "}",
                           device->device_id, watermark);
            emit(out, p->quiet, line);
        }
    }
}

static void accept_frame(es_processor *p, const uint8_t *frame, FILE *out) {
    uint8_t version = frame[2];
    uint8_t flags = frame[3];
    uint32_t device_id = read_u32(frame + 6);
    uint32_t sequence = read_u32(frame + 10);
    uint64_t timestamp = read_u64(frame + 14);
    uint16_t metric = read_u16(frame + 22);
    int32_t raw_value = (int32_t)read_u32(frame + 24);
    int64_t normalized = version == 2 ? (int64_t)raw_value * 10 : raw_value;

    if (metric == ES_METRIC_WATERMARK) {
        emit_silence(p, out, timestamp);
        return;
    }
    if (metric >= ES_MAX_METRICS) {
        emit_reject(p, out, "metric");
        return;
    }

    es_device_state *device = find_device(p, device_id, out);
    if (device == NULL) {
        return;
    }
    if ((flags & ES_FLAG_RESTART) != 0) {
        device->seq_valid = false;
        memset(device->metrics, 0, sizeof(device->metrics));
    }
    if (device->seq_valid) {
        if (sequence == device->last_seq) {
            char line[160];
            (void)snprintf(line, sizeof(line),
                           "{\"type\":\"duplicate\",\"device\":%u,\"sequence\":%u}",
                           device_id, sequence);
            emit(out, p->quiet, line);
            return;
        }
        bool rollover = device->last_seq >= 0xfffffff0u && sequence <= 0x0fu;
        if (!rollover && sequence < device->last_seq) {
            char line[192];
            (void)snprintf(line, sizeof(line),
                           "{\"type\":\"late\",\"device\":%u,\"sequence\":%u,\"last_sequence\":%u}",
                           device_id, sequence, device->last_seq);
            emit(out, p->quiet, line);
            return;
        }
    }

    if (device->silence_alarm) {
        char line[160];
        device->silence_alarm = false;
        (void)snprintf(line, sizeof(line),
                       "{\"type\":\"alarm\",\"alarm\":\"silence\",\"state\":\"clear\",\"device\":%u}",
                       device_id);
        emit(out, p->quiet, line);
    }

    device->seq_valid = true;
    device->last_seq = sequence;
    device->last_timestamp = timestamp;
    es_metric_state *state = &device->metrics[metric];
    state->values[state->next] = (uint32_t)(int32_t)normalized;
    state->next = (uint8_t)((state->next + 1u) % ES_WINDOW_SAMPLES);
    if (state->count < ES_WINDOW_SAMPLES) {
        state->count++;
    }
    int64_t sum = 0;
    for (uint8_t i = 0; i < state->count; ++i) {
        sum += (int32_t)state->values[i];
    }
    int64_t average = sum / state->count;
    p->accepted++;

    char line[256];
    (void)snprintf(line, sizeof(line),
                   "{\"type\":\"event\",\"device\":%u,\"sequence\":%u,\"timestamp\":%" PRIu64 ",\"metric\":%u,\"value_milli\":%" PRId64 ",\"window_average_milli\":%" PRId64 ",\"accepted\":%" PRIu64 "}",
                   device_id, sequence, timestamp, metric, normalized, average, p->accepted);
    emit(out, p->quiet, line);

    bool high = average > 50000;
    bool clear = average <= 45000;
    if (high && !state->high_alarm) {
        state->high_alarm = true;
        (void)snprintf(line, sizeof(line),
                       "{\"type\":\"alarm\",\"alarm\":\"high\",\"state\":\"active\",\"device\":%u,\"metric\":%u,\"average_milli\":%" PRId64 "}",
                       device_id, metric, average);
        emit(out, p->quiet, line);
    } else if (clear && state->high_alarm) {
        state->high_alarm = false;
        (void)snprintf(line, sizeof(line),
                       "{\"type\":\"alarm\",\"alarm\":\"high\",\"state\":\"clear\",\"device\":%u,\"metric\":%u,\"average_milli\":%" PRId64 "}",
                       device_id, metric, average);
        emit(out, p->quiet, line);
    }
}

void es_init(es_processor *p, bool quiet) {
    memset(p, 0, sizeof(*p));
    p->quiet = quiet;
}

int es_process_bytes(es_processor *p, const uint8_t *data, size_t length, FILE *out) {
    if (length > ES_MAX_BUFFER - p->buffered) {
        emit_reject(p, out, "parser_buffer");
        p->buffered = 0;
        return -1;
    }
    memcpy(p->buffer + p->buffered, data, length);
    p->buffered += length;

    size_t offset = 0;
    while (p->buffered - offset >= 2) {
        if (p->buffer[offset] != 0xe5u || p->buffer[offset + 1] != 0x47u) {
            emit_reject(p, out, "junk");
            offset++;
            continue;
        }
        if (p->buffered - offset < 6) {
            break;
        }
        uint16_t frame_length = read_u16(p->buffer + offset + 4);
        if (frame_length != ES_MAX_FRAME_SIZE) {
            emit_reject(p, out, "length");
            offset++;
            continue;
        }
        if (p->buffered - offset < frame_length) {
            break;
        }
        uint8_t version = p->buffer[offset + 2];
        if (version != 1 && version != 2) {
            emit_reject(p, out, "version");
            offset += frame_length;
            continue;
        }
        uint32_t expected = read_u32(p->buffer + offset + 28);
        uint32_t actual = crc32_slow(p->buffer + offset, 28);
        if (expected != actual) {
            emit_reject(p, out, "checksum");
            offset += frame_length;
            continue;
        }
        accept_frame(p, p->buffer + offset, out);
        offset += frame_length;
    }
    if (offset > 0) {
        memmove(p->buffer, p->buffer + offset, p->buffered - offset);
        p->buffered -= offset;
    }
    return 0;
}

int es_finish(es_processor *p, FILE *out) {
    if (p->buffered != 0) {
        emit_reject(p, out, "truncated");
        p->buffered = 0;
        return 1;
    }
    return 0;
}

typedef struct {
    char magic[4];
    uint32_t version;
    uint32_t payload_size;
    uint32_t crc;
} checkpoint_header;

int es_checkpoint(es_processor *p, const char *path, FILE *out, int fail_step) {
    char temporary[1024];
    if (snprintf(temporary, sizeof(temporary), "%s.tmp", path) >= (int)sizeof(temporary)) {
        return -1;
    }
    FILE *file = fopen(temporary, "wb");
    if (file == NULL) {
        return -1;
    }
    checkpoint_header header = {{'E', 'S', 'C', 'P'}, ES_CHECKPOINT_VERSION,
                                (uint32_t)sizeof(*p), crc32_slow((const uint8_t *)p, sizeof(*p))};
    int status = 0;
    if (fail_step == 1 || fwrite(&header, sizeof(header), 1, file) != 1) {
        status = -1;
    } else if (fail_step == 2 || fwrite(p, sizeof(*p), 1, file) != 1) {
        status = -1;
    } else if (fail_step == 3 || fflush(file) != 0) {
        status = -1;
    }
    if (fclose(file) != 0) {
        status = -1;
    }
    if (fail_step == 4) {
        status = -1;
    }
    if (status == 0) {
        if (rename(temporary, path) != 0) {
            status = -1;
        }
    } else {
        (void)remove(temporary);
    }
    char line[160];
    (void)snprintf(line, sizeof(line),
                   "{\"type\":\"checkpoint\",\"status\":\"%s\",\"fail_step\":%d}",
                   status == 0 ? "PASS" : "FAIL", fail_step);
    emit(out, p->quiet, line);
    return status;
}

int es_restore(es_processor *p, const char *path, FILE *out) {
    FILE *file = fopen(path, "rb");
    if (file == NULL) {
        return -1;
    }
    checkpoint_header header;
    es_processor restored;
    int status = 0;
    if (fread(&header, sizeof(header), 1, file) != 1 ||
        memcmp(header.magic, ES_CHECKPOINT_MAGIC, 4) != 0 ||
        header.version != ES_CHECKPOINT_VERSION || header.payload_size != sizeof(restored) ||
        fread(&restored, sizeof(restored), 1, file) != 1 ||
        header.crc != crc32_slow((const uint8_t *)&restored, sizeof(restored))) {
        status = -1;
    }
    (void)fclose(file);
    if (status == 0) {
        bool quiet = p->quiet;
        *p = restored;
        p->quiet = quiet;
    }
    char line[128];
    (void)snprintf(line, sizeof(line), "{\"type\":\"recovery\",\"status\":\"%s\"}",
                   status == 0 ? "PASS" : "FAIL");
    emit(out, p->quiet, line);
    return status;
}

const char *es_implementation_name(void) {
    return "machine-generated";
}
