#!/usr/bin/env python3
"""Generate the EdgeStream machine candidate deterministically."""

from __future__ import annotations

import argparse
from pathlib import Path


def crc_table() -> list[int]:
    values: list[int] = []
    for byte in range(256):
        crc = byte
        for _ in range(8):
            crc = (crc >> 1) ^ (0xEDB88320 if crc & 1 else 0)
        values.append(crc)
    return values


def render_table() -> str:
    values = crc_table()
    rows = []
    for start in range(0, 256, 8):
        row = ", ".join(f"0x{value:08x}u" for value in values[start : start + 8])
        rows.append(f"    {row},")
    return "\n".join(rows)


def generate(reference: str) -> str:
    old_crc = """static uint32_t crc32_slow(const uint8_t *data, size_t length) {
    uint32_t crc = 0xffffffffu;
    for (size_t i = 0; i < length; ++i) {
        crc ^= data[i];
        for (unsigned bit = 0; bit < 8; ++bit) {
            uint32_t mask = (uint32_t)-(int32_t)(crc & 1u);
            crc = (crc >> 1u) ^ (0xedb88320u & mask);
        }
    }
    return ~crc;
}
"""
    new_crc = f"""/* MNCS-GENERATED: table specialized for the declared CRC-32 polynomial. */
static const uint32_t crc32_table[256] = {{
{render_table()}
}};

static uint32_t crc32_slow(const uint8_t *data, size_t length) {{
    uint32_t crc = 0xffffffffu;
    for (size_t i = 0; i < length; ++i) {{
        crc = crc32_table[(crc ^ data[i]) & 0xffu] ^ (crc >> 8u);
    }}
    return ~crc;
}}
"""
    if old_crc not in reference:
        raise ValueError("reference CRC function did not match the generator contract")
    generated = reference.replace(old_crc, new_crc, 1)
    generated = generated.replace('return "reference";', 'return "machine-generated";', 1)
    marker = (
        "/* MNCS-GENERATED\n"
        " * Generated by generator/generate_candidate.py from the readable reference.\n"
        " * Do not edit this file directly.\n"
        " */\n"
    )
    return marker + generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reference", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    source = args.reference.read_text(encoding="utf-8")
    output = generate(source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
