#!/usr/bin/env python3
import hashlib
import json
import pathlib
import subprocess
import sys
import tempfile

root = pathlib.Path(__file__).parent
header = (root / "c/parser.h").read_bytes()
spec = json.loads((root / "generated/binding_spec.json").read_text())
header_hash = hashlib.sha256(header).hexdigest()
raw = f'''// Code generated by tools_generate.py; DO NOT EDIT.\npackage main\n/*\n#cgo CFLAGS: -I../c\n#include "../c/parser.c"\n*/\nimport "C"\nimport "unsafe"\nconst BindingHeaderSHA256 = "{header_hash}"\nconst BindingABIVersion = {spec["abi_version"]}\nfunc parseNative(b []byte) (uint32, int) {{\n if len(b)==0 {{ return 0,1 }}\n var out C.uint32_t\n rc:=C.mncs_parse_u32((*C.uint8_t)(unsafe.Pointer(&b[0])),C.size_t(len(b)),&out)\n return uint32(out),int(rc)\n}}\n'''
with tempfile.NamedTemporaryFile("w+", suffix=".go", delete=False) as temporary:
    temporary.write(raw)
    temporary_name = temporary.name
subprocess.run(["gofmt", "-w", temporary_name], check=True)
output = pathlib.Path(temporary_name).read_text()
pathlib.Path(temporary_name).unlink()
path = root / "go-host/binding_gen.go"
if "--check" in sys.argv:
    raise SystemExit(0 if path.exists() and path.read_text() == output else 1)
path.write_text(output)
