// Code generated by tools_generate.py; DO NOT EDIT.
package main

/*
#cgo CFLAGS: -I../c
#include "../c/parser.c"
*/
import "C"
import "unsafe"

const BindingHeaderSHA256 = "6fb0e2cf5e0bbeb73dbcd6c4fcff7cfc07cc1c66cf7f0d67d249231d12570e5d"
const BindingABIVersion = 1

func parseNative(b []byte) (uint32, int) {
	if len(b) == 0 {
		return 0, 1
	}
	var out C.uint32_t
	rc := C.mncs_parse_u32((*C.uint8_t)(unsafe.Pointer(&b[0])), C.size_t(len(b)), &out)
	return uint32(out), int(rc)
}
