from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / "generator" / "policy-spec.json"
OUTPUT_PATH = ROOT / "machine" / "generated_policy.py"


def render() -> str:
    spec = json.loads(SPEC_PATH.read_text())
    features = list(spec["features"])
    weights = spec["weights"]
    table: list[int] = []
    for mask in range(1 << len(features)):
        rank = int(spec["base_rank"])
        for index, feature in enumerate(features):
            if mask & (1 << index):
                rank += int(weights[feature])
        table.append(rank)

    rows = ",\n    ".join(str(value) for value in table)
    candidate_id = json.dumps(spec["candidate_id"])
    generator_id = json.dumps(spec["generator_id"])
    recent_age_threshold = int(spec["recent_age_threshold"])
    return f"""# Generated by tools/generate_policy.py from generator/policy-spec.json.
# Do not edit by hand; regenerate and preserve the generator identity.
from __future__ import annotations

from dataclasses import dataclass

from cacheforge.model import CacheBlock, CacheState

CANDIDATE_ID = {candidate_id}
GENERATOR_ID = {generator_id}
RECENT_AGE_THRESHOLD = {recent_age_threshold}
EVICTION_RANK = (
    {rows},
)


def _feature_mask(block: CacheBlock, clock: int) -> int:
    mask = 0
    mask |= int(block.kind == "prompt") << 0
    mask |= int(block.shared) << 1
    mask |= int(block.reuse_count >= 2) << 2
    mask |= int(block.group == "sliding") << 3
    mask |= int(clock - block.last_used <= RECENT_AGE_THRESHOLD) << 4
    mask |= int(block.kind == "generated") << 5
    return mask


@dataclass(frozen=True)
class GeneratedEvictionPolicy:
    policy_id: str = CANDIDATE_ID

    def propose(self, state: CacheState, required: int) -> tuple[list[int], int]:
        candidates = [block for block in state.blocks.values() if not block.owners]
        candidates.sort(
            key=lambda block: (
                -EVICTION_RANK[_feature_mask(block, state.clock)],
                block.last_used,
                block.block_id,
            )
        )
        return [block.block_id for block in candidates[:required]], len(candidates)
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text() != expected:
            raise SystemExit("generated policy is stale; run tools/generate_policy.py")
        return 0
    OUTPUT_PATH.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
