# Generated by tools/generate_policy.py from generator/policy-spec.json.
# Do not edit by hand; regenerate and preserve the generator identity.
from __future__ import annotations

from dataclasses import dataclass

from cacheforge.model import CacheBlock, CacheState

CANDIDATE_ID = "cacheforge.machine.eviction-table.v1"
GENERATOR_ID = "cacheforge.eviction-table.generator.v1"
RECENT_AGE_THRESHOLD = 3
EVICTION_RANK = (
    100,
    70,
    10,
    -20,
    50,
    20,
    -40,
    -70,
    120,
    90,
    30,
    0,
    70,
    40,
    -20,
    -50,
    90,
    60,
    0,
    -30,
    40,
    10,
    -50,
    -80,
    110,
    80,
    20,
    -10,
    60,
    30,
    -30,
    -60,
    170,
    140,
    80,
    50,
    120,
    90,
    30,
    0,
    190,
    160,
    100,
    70,
    140,
    110,
    50,
    20,
    160,
    130,
    70,
    40,
    110,
    80,
    20,
    -10,
    180,
    150,
    90,
    60,
    130,
    100,
    40,
    10,
)


def _feature_mask(block: CacheBlock, clock: int) -> int:
    mask = 0
    mask |= int(block.kind == "prompt") << 0
    mask |= int(block.shared) << 1
    mask |= int(block.reuse_count >= 2) << 2
    mask |= int(block.group == "sliding") << 3
    mask |= int(clock - block.last_used <= RECENT_AGE_THRESHOLD) << 4
    mask |= int(block.kind == "generated") << 5
    return mask


@dataclass(frozen=True)
class GeneratedEvictionPolicy:
    policy_id: str = CANDIDATE_ID

    def propose(self, state: CacheState, required: int) -> tuple[list[int], int]:
        candidates = [block for block in state.blocks.values() if not block.owners]
        candidates.sort(
            key=lambda block: (
                -EVICTION_RANK[_feature_mask(block, state.clock)],
                block.last_used,
                block.block_id,
            )
        )
        return [block.block_id for block in candidates[:required]], len(candidates)
